# Generated by Django 5.1.1 on 2024-11-08 05:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='oficiales',
            fields=[
                ('num_placa', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Numero de placa')),
                ('rank', models.CharField(max_length=21, verbose_name='Rango')),
            ],
            options={
                'verbose_name': 'Oficial',
                'verbose_name_plural': 'Oficiales',
            },
        ),
        migrations.CreateModel(
            name='registro_casos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('estatus', models.CharField(max_length=20, verbose_name='Estatus')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Regsitro')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de cerrado')),
                ('num_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comisaria.oficiales', verbose_name='Designado')),
            ],
            options={
                'verbose_name': 'Registro de caso',
                'verbose_name_plural': 'Registros de Casos',
            },
        ),
        migrations.CreateModel(
            name='reportes_caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(verbose_name='Fecha de reporte')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('id_caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comisaria.registro_casos', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Reporte de caso',
                'verbose_name_plural': 'Reportes de casos',
            },
        ),
        migrations.CreateModel(
            name='reportes_de_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de reporte')),
                ('fecha', models.DateField(verbose_name='Fecha de Reporte')),
                ('num_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comisaria.oficiales', verbose_name='Oficial')),
            ],
            options={
                'verbose_name': 'Reporte de servicio',
                'verbose_name_plural': 'Reportes de servicio',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Apellido paterno')),
                ('last_name2', models.CharField(default='', max_length=50, verbose_name='Apellido materno')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('puesto', models.CharField(default='', max_length=30, verbose_name='Puesto')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha de registro')),
                ('num_phone', models.CharField(default='', max_length=14, verbose_name='Telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='oficiales',
            name='id_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID empleado'),
        ),
    ]
