# Generated by Django 5.1.1 on 2024-11-10 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comisaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficiales',
            name='id_emp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID empleado'),
        ),
    ]
